version: "3.9"

services:

  postgres:
    image: pgvector/pgvector:pg17
    container_name: rag-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpassword

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raguser -d ragdb"]
      interval: 10s
      timeout: 5s
      retries: 5


  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rag-rabbitmq
    restart: unless-stopped

    environment:
      RABBITMQ_DEFAULT_USER: raguser
      RABBITMQ_DEFAULT_PASS: ragpassword

    ports:
      # AMQP protocol
      - "5672:5672"

      # Management UI
      - "15672:15672"

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

#  api:
#    build:
#      context: ..
#      dockerfile: RagAgent.Api/Dockerfile
#    container_name: rag-api
#    restart: unless-stopped
#    ports:
#      - "5227:8080"
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ConnectionStrings__DbConnection=Host=postgres;Port=5432;Database=ragdb;Username=raguser;Password=ragpassword
#      - RabbitMq__Host=rabbitmq
#      - Ollama__BaseUrl=http://host.docker.internal:11434
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    depends_on:
#      postgres:
#        condition: service_healthy
#      rabbitmq:
#        condition: service_healthy

volumes:
  postgres_data:
  rabbitmq_data: